### ISSUE TITLE
Created units not updating in realtime

### ISSUE THREAD

**Issue by c1t9b** [Chuckatron/CadvancedBugs#2]
After creating a unit you must refresh or delete a call before it pops up

**Comment by Chuckatron** [comment]
Probably related to: https://github.com/Chuckatron/cadvanced_client/issues/7

**Comment by Chuckatron** [comment]
Fixed in:
https://github.com/Chuckatron/cadvanced_client/commit/1e80cca06d398f6ce6de678259147e9cb382e0d4
https://github.com/Chuckatron/cadvanced_server/commit/3ba378310c641d71516628083693f96d5add86ab
Closing
